import React, { useState, useEffect, useRef } from 'react';
import { 
  Target, 
  Sparkles, 
  CheckCircle2, 
  AlertTriangle, 
  XCircle, 
  Info, 
  FileText, 
  ArrowRight, 
  FolderGit2, 
  ExternalLink, 
  Layers, 
  Code2, 
  Terminal, 
  Database, 
  Cloud, 
  Cpu, 
  Wrench, 
  Award, 
  Check, 
  AlertCircle,
  HelpCircle,
  ChevronDown,
  ChevronUp,
  RotateCcw,
  Wand2,
  Briefcase
} from 'lucide-react';
import { analyzeJobMatch, generateJobDescriptionApi } from '../services/api.js';

// Category icon helper
function getCategoryIcon(category = '') {
  const cat = category.toLowerCase();
  if (cat.includes('program') || cat.includes('language')) return <Code2 size={15} color="var(--accent-secondary)" />;
  if (cat.includes('front')) return <Layers size={15} color="#60a5fa" />;
  if (cat.includes('back')) return <Terminal size={15} color="#34d399" />;
  if (cat.includes('database')) return <Database size={15} color="#fbbf24" />;
  if (cat.includes('cloud')) return <Cloud size={15} color="#38bdf8" />;
  if (cat.includes('devops')) return <Cpu size={15} color="#a78bfa" />;
  if (cat.includes('tool')) return <Wrench size={15} color="#f472b6" />;
  return <Award size={15} color="var(--accent-primary)" />;
}

// Sample job descriptions for quick testing
const SAMPLE_JDS = [
  {
    title: 'Full-Stack Software Engineer',
    text: `Job Title: Full-Stack Software Engineer
Department: Engineering

About the Role:
We are looking for a skilled Full-Stack Software Engineer to build and scale our web applications.

Required Qualifications:
- Strong proficiency in JavaScript, TypeScript, and modern React.
- Production experience with Node.js and Express backend services.
- Solid experience with relational databases such as PostgreSQL and MongoDB.
- Practical knowledge of Git version control and Docker containerization.

Preferred Qualifications:
- Experience with Python and FastAPI is a plus.
- Familiarity with TailwindCSS and Next.js.
- Exposure to AWS cloud infrastructure and CI/CD pipelines.`
  },
  {
    title: 'Backend Python Engineer',
    text: `Role: Senior Backend Engineer

Responsibilities:
Design, develop, and maintain high-throughput backend microservices.

Requirements:
- Minimum 3+ years writing robust Python applications.
- In-depth expertise in PostgreSQL, Redis, and database query optimization.
- Hands-on experience with Docker, Linux environments, and Git.
- Deep understanding of RESTful API design.

Nice to Have:
- Experience with Kubernetes and Go.
- Familiarity with TypeScript and React for internal tooling.`
  }
];

export default function JobMatchSection({ claimedSkills = [], crossVerification = null, sessionId = '', onMatchAnalyzed = null }) {
  const [jobDescription, setJobDescription] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedJd, setGeneratedJd] = useState(null);
  const [generationError, setGenerationError] = useState('');
  const [error, setError] = useState('');
  const [matchResult, setMatchResult] = useState(null);
  const [showFormulaDetails, setShowFormulaDetails] = useState(false);

  const autoGeneratedOnceRef = useRef(false);
  const prevSkillsSigRef = useRef('');

  const handleAnalyze = async (overrideText = null) => {
    const textToAnalyze = typeof overrideText === 'string' ? overrideText : jobDescription;
    if (!textToAnalyze || !textToAnalyze.trim()) {
      setError('Please paste or enter a job description to analyze.');
      return;
    }
    if (textToAnalyze.trim().length < 30) {
      setError('Job description is too short. Please enter at least 30 characters.');
      return;
    }

    setError('');
    setIsLoading(true);

    try {
      const data = await analyzeJobMatch({
        jobDescription: textToAnalyze.trim(),
        sessionId,
        claimedSkills,
        verifiedSkills: claimedSkills,
        crossVerification
      });
      setMatchResult(data);
      if (onMatchAnalyzed) {
        onMatchAnalyzed(data);
      }
    } catch (err) {
      setError(err.message || 'Failed to analyze job match. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const handleGenerateJd = async () => {
    setIsGenerating(true);
    setGenerationError('');
    try {
      const data = await generateJobDescriptionApi({
        skills: claimedSkills,
        sessionId
      });
      setGeneratedJd(data);
      if (data?.jobDescriptionText) {
        setJobDescription(data.jobDescriptionText);
        // Automatically analyze the generated JD to trigger downstream match, gaps, growth, and AI analysis
        await handleAnalyze(data.jobDescriptionText);
      }
    } catch (err) {
      setGenerationError(err.message || 'Failed to generate job description.');
    } finally {
      setIsGenerating(false);
    }
  };

  // Auto-generate once when component mounts if candidate has verified skills and editor is empty
  useEffect(() => {
    if (autoGeneratedOnceRef.current) return;
    const hasProven = claimedSkills.some(s => {
      const status = (s.status || s.verificationStatus || '').toLowerCase();
      return status === 'proven' || status === 'proved';
    });
    if (hasProven && !jobDescription) {
      autoGeneratedOnceRef.current = true;
      handleGenerateJd();
    }
  }, [claimedSkills]);

  // Reactive data flow: when verified skills change, update Job Description and re-analyze Job Match
  useEffect(() => {
    const currentSig = (claimedSkills || [])
      .map(s => `${s.skill || s.name}:${s.status}:${s.evidence?.length || 0}`)
      .sort()
      .join('|');

    if (!prevSkillsSigRef.current) {
      prevSkillsSigRef.current = currentSig;
      return;
    }

    if (prevSkillsSigRef.current !== currentSig) {
      prevSkillsSigRef.current = currentSig;
      // If a generated JD was active, re-generate it to include new verified skills
      if (generatedJd) {
        handleGenerateJd();
      } else if (jobDescription && jobDescription.trim().length >= 30) {
        handleAnalyze();
      }
    }
  }, [claimedSkills]);

  const charCount = jobDescription.length;
  const isTooShort = charCount > 0 && charCount < 30;

  const handleLoadSample = (sampleText) => {
    setJobDescription(sampleText);
    setError('');
  };

  const handleClear = () => {
    setJobDescription('');
    setMatchResult(null);
    setError('');
  };

  const match = matchResult?.match || matchResult;
  const matchPercentage = match?.percentage ?? matchResult?.summary?.matchPercentage ?? 0;

  const matchedSkillsList = match?.matchedSkills || matchResult?.matchedSkills || [];
  const partialSkillsList = match?.partialSkills || matchResult?.partialSkills || [];
  const gapSkillsList = match?.gapSkills || matchResult?.skillGaps || [];
  const claimedUnverifiedSkillsList = match?.claimedUnverifiedSkills || [];
  const responsibilitiesList = match?.responsibilities || [];
  const factualExplanation = match?.explanation || '';
  const totalRequired = match?.requiredSkills?.length ?? matchResult?.summary?.totalRequired ?? (matchedSkillsList.length + partialSkillsList.length + gapSkillsList.length);
  const totalPreferred = match?.preferredSkills?.length ?? matchResult?.summary?.totalPreferred ?? 0;

  // Match score rating
  const getRating = (pct) => {
    if (pct >= 80) return { label: 'Strong Fit', color: '#10b981', desc: 'Direct empirical evidence strongly aligns with required competencies.' };
    if (pct >= 50) return { label: 'Moderate Fit', color: '#f59e0b', desc: 'Good baseline alignment with several partially supported skills or gaps.' };
    return { label: 'Low Evidence Alignment', color: '#ef4444', desc: 'Significant gap between required skills and observable GitHub proof.' };
  };

  const rating = getRating(matchPercentage);

  return (
    <section id="job-match-section" className="job-match-card">
      {/* Stage Header */}
      <div className="skills-stage-header">
        <div>
          <span className="skills-stage-badge job-match-badge">
            <Target size={16} />
            <span>Stage 6B & 6C: Job Match Engine & Automatic JD</span>
          </span>
          <h3 style={{ fontSize: '1.5rem', marginTop: '0.65rem' }}>
            JOB MATCH ANALYSIS
          </h3>
          <p className="job-match-intro">
            Compare target job description requirements against resume claimed skills and observable GitHub evidence for deterministic qualification scoring.
          </p>
        </div>
      </div>

      {/* ========================================================
          Stage 6C: Automatic Job Description Generator
          ======================================================== */}
      <div className="job-generator-card">
        <div className="job-generator-header">
          <div className="job-generator-title-wrap">
            <div className="job-generator-icon">
              <Wand2 size={20} />
            </div>
            <div>
              <h4 className="job-generator-title">
                Automatic Job Description Generator
              </h4>
              <p className="job-generator-subtitle">
                Deterministically maps your strongest verified technical evidence to an ideal target role & tailored job description.
              </p>
            </div>
          </div>

          <button
            id="generate-jd-btn"
            type="button"
            className="btn-generate-jd"
            onClick={handleGenerateJd}
            disabled={isGenerating}
          >
            {isGenerating ? (
              <>
                <span className="btn-spinner" />
                <span>Generating JD...</span>
              </>
            ) : (
              <>
                <Sparkles size={16} />
                <span>Generate Job Description</span>
              </>
            )}
          </button>
        </div>

        {generationError && (
          <div className="job-match-error-banner" style={{ marginTop: '1rem' }}>
            <AlertCircle size={18} style={{ flexShrink: 0 }} />
            <span>{generationError}</span>
          </div>
        )}

        {/* Fallback if 0 proven skills */}
        {generatedJd && generatedJd.role === 'Insufficient Verified Skills' && (
          <div className="generated-fallback-card">
            <AlertTriangle size={20} style={{ flexShrink: 0, marginTop: '2px' }} />
            <div>
              <div className="generated-fallback-title">Insufficient Verified Skills Detected</div>
              <div className="generated-fallback-msg">{generatedJd.summary}</div>
            </div>
          </div>
        )}

        {/* Successful JD Generation Preview */}
        {generatedJd && generatedJd.role !== 'Insufficient Verified Skills' && (
          <div className="generated-jd-preview">
            <div className="generated-role-banner">
              <div className="generated-role-name">
                <Briefcase size={18} />
                <span>Target Role: {generatedJd.role}</span>
              </div>
              <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center', flexWrap: 'wrap' }}>
                <span className="generated-role-badge">
                  {generatedJd.department || 'Engineering'}
                </span>
                <span className="generated-role-badge" style={{ background: 'rgba(99, 102, 241, 0.15)', borderColor: 'rgba(99, 102, 241, 0.35)', color: '#818cf8' }}>
                  Derived from Verified Skills
                </span>
              </div>
            </div>

            <p className="generated-jd-summary">
              {generatedJd.summary}
            </p>

            <div className="generated-skills-container">
              {generatedJd.requiredSkills?.length > 0 && (
                <div className="generated-skills-group">
                  <span className="generated-skills-label" style={{ color: '#34d399' }}>
                    Required (Proven):
                  </span>
                  {generatedJd.requiredSkills.map((skill, idx) => (
                    <span key={idx} className="chip-proven">
                      <CheckCircle2 size={13} />
                      <span>{skill}</span>
                    </span>
                  ))}
                </div>
              )}

              {generatedJd.preferredSkills?.length > 0 && (
                <div className="generated-skills-group">
                  <span className="generated-skills-label" style={{ color: '#93c5fd' }}>
                    Preferred (Secondary):
                  </span>
                  {generatedJd.preferredSkills.map((skill, idx) => (
                    <span key={idx} className="chip-partial">
                      <Info size={13} />
                      <span>{skill}</span>
                    </span>
                  ))}
                </div>
              )}

              {generatedJd.technologies?.length > 0 && (
                <div className="generated-skills-group">
                  <span className="generated-skills-label" style={{ color: '#cbd5e1' }}>
                    Relevant Tech:
                  </span>
                  <span style={{ fontSize: '0.85rem', color: '#e2e8f0' }}>
                    {generatedJd.technologies.join(' • ')}
                  </span>
                </div>
              )}
            </div>

            <div className="generated-jd-instructions">
              <Sparkles size={16} color="#818cf8" style={{ flexShrink: 0 }} />
              <span>
                Job description populated into the editor below. Click <strong>"Analyze Job Match"</strong> below to evaluate your verified evidence against this target role.
              </span>
            </div>
          </div>
        )}
      </div>

      {/* Input Section */}
      <div className="job-input-box">
        <div className="job-input-top-bar">
          <label htmlFor="job-description-textarea" className="job-input-label">
            <FileText size={16} color="var(--accent-secondary)" />
            <span>Paste Job Description</span>
          </label>
          <div className="sample-jd-buttons">
            <span className="sample-label">Quick Load:</span>
            {SAMPLE_JDS.map((sample, idx) => (
              <button
                key={idx}
                type="button"
                className="btn-sample-jd"
                onClick={() => handleLoadSample(sample.text)}
              >
                {sample.title}
              </button>
            ))}
          </div>
        </div>

        <textarea
          id="job-description-textarea"
          className={`job-textarea ${isTooShort ? 'input-warning' : ''}`}
          rows={6}
          placeholder="Paste the target job description or requirements section here (minimum 30 characters)...&#10;Example: 'We are seeking a Full-Stack Engineer with Python, React, PostgreSQL, and Docker...'"
          value={jobDescription}
          onChange={(e) => {
            setJobDescription(e.target.value);
            if (error) setError('');
          }}
        />

        <div className="job-input-bottom-bar">
          <div className="char-counter-wrap">
            <span className={`char-counter ${isTooShort ? 'char-counter-warn' : ''}`}>
              {charCount.toLocaleString()} / 50,000 characters
            </span>
            {isTooShort && (
              <span className="char-warn-msg">Minimum 30 characters required</span>
            )}
          </div>

          <div className="job-action-buttons">
            {jobDescription && (
              <button
                type="button"
                className="btn-clear-jd"
                onClick={handleClear}
                disabled={isLoading}
              >
                <RotateCcw size={14} />
                <span>Clear</span>
              </button>
            )}
            <button
              id="analyze-job-match-btn"
              type="button"
              className="btn-analyze-match"
              onClick={handleAnalyze}
              disabled={isLoading || charCount === 0}
            >
              {isLoading ? (
                <>
                  <span className="btn-spinner" />
                  <span>Analyzing Match...</span>
                </>
              ) : (
                <>
                  <Sparkles size={16} />
                  <span>Analyze Job Match</span>
                </>
              )}
            </button>
          </div>
        </div>

        {error && (
          <div className="job-match-error-banner">
            <AlertCircle size={18} style={{ flexShrink: 0 }} />
            <span>{error}</span>
          </div>
        )}
      </div>

      {/* ========================================================
          Job Match Results View
          ======================================================== */}
      {/* ========================================================
          Job Match Results View
          ======================================================== */}
      {matchResult && (
        <div className="job-match-results-container">
          
          {/* Summary Scorecard Grid */}
          <div className="match-summary-card">
            {/* Left: Radial / Ring Match Percentage */}
            <div className="match-ring-column">
              <div className="match-score-circle" style={{ borderColor: rating.color }}>
                <div className="match-score-inner">
                  <span className="match-score-number" style={{ color: rating.color }}>
                    {matchPercentage}%
                  </span>
                  <span className="match-score-sublabel">Verified Skill Match</span>
                </div>
              </div>
              <div className="match-score-badge" style={{ backgroundColor: `${rating.color}1a`, color: rating.color, borderColor: `${rating.color}40` }}>
                {rating.label}
              </div>
              <p className="match-score-desc">
                {rating.desc}
              </p>
            </div>

            {/* Right: Key Metrics Strip */}
            <div className="match-kpis-column">
              <div className="match-kpis-grid">
                <div className="match-kpi-item kpi-total">
                  <span className="kpi-num">{totalRequired}</span>
                  <span className="kpi-label">Required Skills</span>
                </div>
                <div className="match-kpi-item kpi-matched">
                  <span className="kpi-num">{matchedSkillsList.length}</span>
                  <span className="kpi-label">Matched</span>
                </div>
                <div className="match-kpi-item kpi-partial">
                  <span className="kpi-num">{partialSkillsList.length}</span>
                  <span className="kpi-label">Partial</span>
                </div>
                <div className="match-kpi-item kpi-gaps">
                  <span className="kpi-num">{gapSkillsList.length}</span>
                  <span className="kpi-label">Gaps</span>
                </div>
                {totalPreferred > 0 && (
                  <div className="match-kpi-item kpi-preferred">
                    <span className="kpi-num">{totalPreferred}</span>
                    <span className="kpi-label">Preferred Skills</span>
                  </div>
                )}
              </div>

              {/* Progress bar visual */}
              <div className="match-progress-wrap">
                <div className="match-progress-labels">
                  <span>Required Skills Evidence Coverage</span>
                  <span><strong>{matchedSkillsList.length + partialSkillsList.length}</strong> of {totalRequired} supported</span>
                </div>
                <div className="match-progress-bar">
                  <div 
                    className="match-progress-fill-matched"
                    style={{ width: `${totalRequired > 0 ? (matchedSkillsList.length / totalRequired) * 100 : 0}%` }}
                    title={`Proven: ${matchedSkillsList.length}`}
                  />
                  <div 
                    className="match-progress-fill-partial"
                    style={{ width: `${totalRequired > 0 ? (partialSkillsList.length / totalRequired) * 100 : 0}%` }}
                    title={`Partial: ${partialSkillsList.length}`}
                  />
                </div>
              </div>

              {/* Factual Explanation below percentage & metrics */}
              {factualExplanation && (
                <div className="job-match-factual-explanation">
                  {factualExplanation}
                </div>
              )}

              {/* Formula & Transparency Toggle */}
              <div className="formula-toggle-box">
                <button
                  type="button"
                  className="btn-formula-toggle"
                  onClick={() => setShowFormulaDetails(!showFormulaDetails)}
                >
                  <Info size={15} color="var(--accent-secondary)" />
                  <span>Why this score? (Deterministic Calculation)</span>
                  {showFormulaDetails ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
                </button>

                {showFormulaDetails && (
                  <div className="formula-explanation-panel">
                    <div className="formula-math-row">
                      <code>
                        Score = Math.round((({matchedSkillsList.length} × 100 + {partialSkillsList.length} × 50) / ({totalRequired || 1} × 100)) × 100) = {matchPercentage}%
                      </code>
                    </div>
                    <ul className="formula-rules-list">
                      <li>
                        <strong>PROVEN Skills (100 points):</strong> Supported directly by candidate's verified evidence.
                      </li>
                      <li>
                        <strong>PARTIAL Skills (50 points):</strong> Partial supporting evidence detected.
                      </li>
                      <li>
                        <strong>CLAIMED-ONLY / MISSING (0 points):</strong> Claimed without verified evidence or missing from candidate profile. Never increases verified match score.
                      </li>
                      <li>
                        <strong>Preferred Skills:</strong> Evaluated separately as bonus signals and do not dilute required score.
                      </li>
                    </ul>
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* ========================================================
              Section 1: MATCHED SKILLS (PROVEN - Green)
              ======================================================== */}
          <div className="match-group-section group-matched">
            <div className="match-group-header">
              <div className="match-group-title">
                <CheckCircle2 size={18} color="#10b981" />
                <span>MATCHED SKILLS</span>
                <span className="match-group-count count-green">{matchedSkillsList.length}</span>
              </div>
              <span className="match-points-tag tag-green">PROVEN • 100 pts</span>
            </div>

            {matchedSkillsList.length === 0 ? (
              <div className="match-group-empty">
                No required skills met full empirical proof criteria.
              </div>
            ) : (
              <div className="match-cards-grid">
                {matchedSkillsList.map((item) => (
                  <div key={item.skill} className="match-item-card card-matched">
                    <div className="match-card-head">
                      <div className="match-skill-name-wrap">
                        {getCategoryIcon(item.category)}
                        <span className="match-skill-name">✓ {item.skill}</span>
                        <span className="match-cat-label">{item.category}</span>
                      </div>
                      <span className="match-status-badge status-proved">PROVEN</span>
                    </div>

                    <p className="match-card-desc">
                      {item.explanation || 'Verified evidence available'}
                    </p>

                    {item.repositories && item.repositories.length > 0 && (
                      <div className="match-card-evidence">
                        <div className="evidence-heading">Observable Proof:</div>
                        <div className="evidence-repo-links">
                          {item.repositories.map((repo) => (
                            <span key={repo} className="repo-proof-pill">
                              <FolderGit2 size={12} />
                              <span>{repo}</span>
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* ========================================================
              Section 2: PARTIAL SKILLS (PARTIAL - Yellow)
              ======================================================== */}
          <div className="match-group-section group-partial">
            <div className="match-group-header">
              <div className="match-group-title">
                <AlertTriangle size={18} color="#f59e0b" />
                <span>PARTIAL SKILLS</span>
                <span className="match-group-count count-amber">{partialSkillsList.length}</span>
              </div>
              <span className="match-points-tag tag-amber">PARTIAL • 50 pts</span>
            </div>

            {partialSkillsList.length === 0 ? (
              <div className="match-group-empty">
                No required skills classified as partial.
              </div>
            ) : (
              <div className="match-cards-grid">
                {partialSkillsList.map((item) => (
                  <div key={item.skill} className="match-item-card card-partial">
                    <div className="match-card-head">
                      <div className="match-skill-name-wrap">
                        {getCategoryIcon(item.category)}
                        <span className="match-skill-name">◐ {item.skill}</span>
                        <span className="match-cat-label">{item.category}</span>
                      </div>
                      <span className="match-status-badge status-partial">PARTIAL</span>
                    </div>

                    <p className="match-card-desc">
                      {item.explanation || 'Some supporting evidence found'}
                    </p>

                    {item.repositories && item.repositories.length > 0 && (
                      <div className="match-card-evidence">
                        <div className="evidence-heading">Observable Proof:</div>
                        <div className="evidence-repo-links">
                          {item.repositories.map((repo) => (
                            <span key={repo} className="repo-proof-pill">
                              <FolderGit2 size={12} />
                              <span>{repo}</span>
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* ========================================================
              Section 3: SKILL GAPS (NOT VERIFIED - Red)
              ======================================================== */}
          <div className="match-group-section group-gap">
            <div className="match-group-header">
              <div className="match-group-title">
                <XCircle size={18} color="#ef4444" />
                <span>SKILL GAPS</span>
                <span className="match-group-count count-red">{gapSkillsList.length}</span>
              </div>
              <span className="match-points-tag tag-red">NOT VERIFIED • 0 pts</span>
            </div>

            {gapSkillsList.length === 0 ? (
              <div className="match-group-empty" style={{ color: '#10b981' }}>
                <Check size={16} />
                <span>All required skills are supported with verified evidence!</span>
              </div>
            ) : (
              <div className="match-cards-grid">
                {gapSkillsList.map((item) => (
                  <div key={item.skill} className="match-item-card card-gap">
                    <div className="match-card-head">
                      <div className="match-skill-name-wrap">
                        {getCategoryIcon(item.category)}
                        <span className="match-skill-name">✕ {item.skill}</span>
                        <span className="match-cat-label">{item.category}</span>
                      </div>
                      <span className={`match-status-badge ${item.status === 'CLAIMED-ONLY' ? 'status-claimed' : 'status-missing'}`}>
                        {item.status === 'CLAIMED-ONLY' ? 'CLAIMED-ONLY' : (item.status === 'NO EVIDENCE' ? 'NO EVIDENCE' : 'NOT VERIFIED')}
                      </span>
                    </div>

                    <p className="match-card-desc">
                      {item.explanation || 'No supporting evidence found'}
                    </p>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* ========================================================
              Section 4: CLAIMED BUT UNVERIFIED (CLAIMED-ONLY)
              ======================================================== */}
          {claimedUnverifiedSkillsList.length > 0 && (
            <div className="match-group-section group-claimed">
              <div className="match-group-header">
                <div className="match-group-title">
                  <AlertCircle size={18} color="#f59e0b" />
                  <span>CLAIMED BUT UNVERIFIED</span>
                  <span className="match-group-count count-amber">{claimedUnverifiedSkillsList.length}</span>
                </div>
                <span className="match-points-tag tag-amber">CLAIMED-ONLY • Evidence Required</span>
              </div>

              <div className="match-cards-grid">
                {claimedUnverifiedSkillsList.map((item) => (
                  <div key={item.skill} className="match-item-card card-claimed">
                    <div className="match-card-head">
                      <div className="match-skill-name-wrap">
                        {getCategoryIcon(item.category)}
                        <span className="match-skill-name">{item.skill}</span>
                        <span className="match-cat-label">{item.category || 'Other'}</span>
                      </div>
                      <span className="match-status-badge status-claimed">CLAIMED-ONLY</span>
                    </div>

                    <p className="match-card-desc">
                      {item.explanation || 'Evidence required'}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* ========================================================
              Section 5: JOB RESPONSIBILITIES & TECHNICAL SUPPORT
              ======================================================== */}
          {responsibilitiesList.length > 0 && (
            <div className="match-group-section" style={{ borderColor: 'rgba(99, 102, 241, 0.3)' }}>
              <div className="match-group-header">
                <div className="match-group-title">
                  <Briefcase size={18} color="#818cf8" />
                  <span>JOB RESPONSIBILITIES</span>
                  <span className="match-group-count" style={{ background: 'rgba(99, 102, 241, 0.2)', color: '#818cf8' }}>
                    {responsibilitiesList.length}
                  </span>
                </div>
                <span className="match-points-tag" style={{ background: 'rgba(99, 102, 241, 0.15)', color: '#818cf8' }}>
                  Factual Alignment
                </span>
              </div>

              <div className="responsibilities-match-list">
                {responsibilitiesList.map((resp, idx) => (
                  <div key={idx} className="resp-item-card">
                    <span className="resp-text">{resp.responsibility}</span>
                    <span className={`resp-badge resp-badge-${resp.status}`}>
                      {resp.explanation}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

        </div>
      )}
    </section>
  );
}
